name: get_devicetype_onex
description: A new Flutter plugin project.
version: 1.0.0
homepage: www.google.com

environment:
  sdk: ">=3.1.2 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.example.get_devicetype_onex
        pluginClass: GetDevicetypeOnexPlugin
      ios:
        pluginClass: GetDevicetypeOnexPlugin
      linux:
        pluginClass: GetDevicetypeOnexPlugin
      macos:
        pluginClass: GetDevicetypeOnexPlugin
      windows:
        pluginClass: GetDevicetypeOnexPluginCApi
